%% Create parameter structure file for fmincon search

function modelfit_param_structure_create()

rp = '/home/radachi/research/CD/';

%1%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i=1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main1';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-1.6,-0.8]; thetaL_ub = -0.1; thetaL_lb = -3.9;
param(i).x0 = allcomb(x,y,thetaH,thetaL);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb];
%2%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i=i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main2';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
param(i).x0 = allcomb(x,y,theta);
param(i).ub = [x_ub,y_ub,theta_ub];
param(i).lb = [x_lb,y_lb,theta_lb];
%3%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main7';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(x,y,theta,k);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb];
%4%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main9';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-1.6,-0.8]; thetaL_ub = -0.1; thetaL_lb = -3.9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb];
%5%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%6%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main20';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,alpha_lb,beta_lb,delta_lb];
%7%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%8%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main22';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,alpha_lb,beta_lb,delta_lb];
%9%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%10%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main20';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,alpha_lb,beta_lb,delta_lb];
%11%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main21';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%12%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main22';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,alpha_lb,beta_lb,delta_lb];
%13%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main10';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%14%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main13';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,alpha_lb,beta_lb,delta_lb];
%15%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main14';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%16%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main8';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,alpha_lb,beta_lb,delta_lb];
%17%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main10';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%18%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main13';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,alpha_lb,beta_lb,delta_lb];
%19%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main14';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [3,7]; thetaH_ub = 10; thetaH_lb = 0.1;
thetaL = [-3,-7]; thetaL_ub = -0.1; thetaL_lb = -10;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%20%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main8';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,alpha_lb,beta_lb,delta_lb];
%21%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main15';
param(i).methodName = 4;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-0.8,-1.6]; thetaL_ub = -0.1; thetaL_lb = -3.9;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,T);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,T_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,T_lb];
%22%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main15';
param(i).methodName = 5;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-0.8,-1.6]; thetaL_ub = -0.1; thetaL_lb = -3.9;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,T);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,T_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,T_lb];
%23%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main16';
param(i).methodName = 4;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,theta,T);
param(i).ub = [x_ub,y_ub,theta_ub,T_ub];
param(i).lb = [x_lb,y_lb,theta_lb,T_lb];
%24%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main16';
param(i).methodName = 5;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,theta,T);
param(i).ub = [x_ub,y_ub,theta_ub,T_ub];
param(i).lb = [x_lb,y_lb,theta_lb,T_lb];
%25%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main17';
param(i).methodName = 4;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,T);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,T_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,T_lb];
%26%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main17';
param(i).methodName = 5;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [0.8,1.6]; theta_ub = 3.9; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,T);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,T_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,T_lb];
%27%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main18';
param(i).methodName = 4;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-0.8,-1.6]; thetaL_ub = -0.1; thetaL_lb = -3.9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,T);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,T_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,T_lb];
%28%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main18';
param(i).methodName = 5;
param(i).distanceTime = 5;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
thetaH = [0.8,1.6]; thetaH_ub = 3.9; thetaH_lb = 0.1;
thetaL = [-0.8,-1.6]; thetaL_ub = -0.1; thetaL_lb = -3.9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
T = [3,6]; T_ub = 10; T_lb = 0;
param(i).x0 = allcomb(x,y,thetaH,thetaL,k,T);
param(i).ub = [x_ub,y_ub,thetaH_ub,thetaL_ub,k_ub,T_ub];
param(i).lb = [x_lb,y_lb,thetaH_lb,thetaL_lb,k_lb,T_lb];
%29%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main2';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%30%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main3';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%31%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main4';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,k);
param(i).ub = [theta_ub,h_ub,k_ub];
param(i).lb = [theta_lb,h_lb,k_lb];
%32%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main5';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,T,k);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb];
%33%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main2';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%34%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main3';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%35%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main4';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,k);
param(i).ub = [theta_ub,h_ub,k_ub];
param(i).lb = [theta_lb,h_lb,k_lb];
%36%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main5';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,T,k);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb];
%37%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main2';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%38%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main3';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%39%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main4';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,k);
param(i).ub = [theta_ub,h_ub,k_ub];
param(i).lb = [theta_lb,h_lb,k_lb];
%40%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main5';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,T,k);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb];
%41%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main2';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%42%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main3';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%43%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main4';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,k);
param(i).ub = [theta_ub,h_ub,k_ub];
param(i).lb = [theta_lb,h_lb,k_lb];
%44%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main5';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.2,0.3]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
param(i).x0 = allcomb(theta,h,T,k);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb];
%45%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%46%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main20';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%47%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%48%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main22';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%49%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main19';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%50%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main20';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%51%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%52%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main22';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%53%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%54%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main20';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%55%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%56%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main22';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%57%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main19';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%58%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main20';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%59%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main21';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%60%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen5';
param(i).fitName = 'main22';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%61%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main31';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%62%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main32';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%63%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main33';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%64%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%65%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main31';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%66%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main32';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%67%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main33';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%68%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%69%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main31';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%70%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main32';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%71%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main33';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%72%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%73%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main31';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%74%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main32';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%75%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main33';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%76%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%77%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main31';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%78%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main32';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%79%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main33';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%80%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main34';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%81%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main31';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%82%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main32';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%83%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main33';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
param(i).x0 = allcomb(theta,h);
param(i).ub = [theta_ub,h_ub];
param(i).lb = [theta_lb,h_lb];
%84%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main34';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%85%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main35';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%86%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main36';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%87%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main35';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%88%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main36';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%89%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main35';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%90%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main36';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%91%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main35';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%92%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main36';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%93%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main35';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%94%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main36';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%95%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main35';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%96%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main36';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%97%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main37';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%98%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main38';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%99%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main37';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%100%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main38';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%101%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main37';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%102%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main38';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%103%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main37';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%104%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main38';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%105%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main37';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%106%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main38';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%107%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main37';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,alpha_lb,beta_lb,delta_lb];
%108%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay5';
param(i).fitName = 'main38';
param(i).methodName = 3;
param(i).distanceTime = 5;
param(i).cond = '_pred';
theta = [0.5,0.9]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,T,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,T_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,T_lb,alpha_lb,beta_lb,delta_lb];
%109%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%110%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%111%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main32';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '';
theta = [0.5]; theta_ub = 0.5; theta_lb = 0.5;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%112%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%113%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main23';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '_pred';
thetaH = [0.5,0.7]; thetaH_ub = 2; thetaH_lb = 0;
thetaL = [-0.5,-0.7]; thetaL_ub = 0; thetaL_lb = -2;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(thetaH,thetaL,h,k,alpha,beta,delta);
param(i).ub = [thetaH_ub,thetaL_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [thetaH_lb,thetaL_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%114%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'opt';
param(i).methodName = 1;
param(i).distanceTime = 5;
param(i).cond = '';
theta = [0.15,0.2,0.25,0.3,0.35]'; theta_ub = 0.5; theta_lb = 0;
param(i).x0 = theta;
param(i).ub = theta_ub;
param(i).lb = theta_lb;
%115%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'opt';
param(i).methodName = 2;
param(i).distanceTime = 5;
param(i).cond = '';
theta = [0.15,0.2,0.25,0.3,0.35]'; theta_ub = 0.5; theta_lb = 0;
param(i).x0 = theta;
param(i).ub = theta_ub;
param(i).lb = theta_lb;
%116%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%117%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%118%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%119%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%120%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%121%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%122%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%123%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'heuristic1';
param(i).fitName = 'main19';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '_pred';
x = [2,5]; x_ub = 10; x_lb = 1;
y = [4,8]; y_ub = 20; y_lb = 1;
theta = [3,7]; theta_ub = 10; theta_lb = 0.1;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.2,0.6]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(x,y,theta,k,alpha,beta,delta);
param(i).ub = [x_ub,y_ub,theta_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [x_lb,y_lb,theta_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%124%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%125%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'adamsmackay3';
param(i).fitName = 'main34';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '_pred';
theta = [0.3,0.7]; theta_ub = 1; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
T = [4,8]; T_ub = 20; T_lb = 1;
param(i).x0 = allcomb(theta,h,T);
param(i).ub = [theta_ub,h_ub,T_ub];
param(i).lb = [theta_lb,h_lb,T_lb];
%126%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 3;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];
%127%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
i = i+1;
param(i).modelName = 'yucohen4';
param(i).fitName = 'main21';
param(i).methodName = 1;
param(i).distanceTime = 7;
param(i).cond = '_pred';
theta = [0.5,0.7]; theta_ub = 2; theta_lb = 0;
h = [-2.5,-5]; h_ub = -1; h_lb = -9;
k = [-0.3,0.3]; k_ub = 1; k_lb = -1;
alpha = [20,40]; alpha_ub = 100; alpha_lb = 5;
beta = [5,15]; beta_ub = 200; beta_lb = 1;
delta = [0.3,0.7]; delta_ub = 1; delta_lb = 0;
param(i).x0 = allcomb(theta,h,k,alpha,beta,delta);
param(i).ub = [theta_ub,h_ub,k_ub,alpha_ub,beta_ub,delta_ub];
param(i).lb = [theta_lb,h_lb,k_lb,alpha_lb,beta_lb,delta_lb];

save([rp 'analysis/modelfit_param_structure.mat'],'param');

end
